Update 101-compile

diff --git a/python-hello_world/101-compile b/python-hello_world/101-compile
--- a/python-hello_world/101-compile
+++ b/python-hello_world/101-compile
@@ -1,24 +1,6 @@
-#!/bin/bash
+#!/usr/bin/env bash
 if [ -z "$PYFILE" ]; then
     echo "Error: PYFILE environment variable is not set."
     exit 1
 fi
-
-if [ ! -f "$PYFILE" ]; then
-    echo "Error: $PYFILE not found."
-    exit 1
-fi
-
-filename=$(basename "$PYFILE")
-file_base="${filename%.*}"
-
-output_file="$file_base.pyc"
-
-python3 -m py_compile -o "$output_file" "$PYFILE"
-
-if [ $? -eq 0 ]; then
-    echo "Compiling $PYFILE ..."
-else
-    echo "Compilation of $PYFILE failed."
-    exit 1
-fi
+python3 -m py_compile "$PYFILE" && echo "Compiling $PYFILE ..." || echo "Compilation of $PYFILE failed."
